// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StayMate.Models;

#nullable disable

namespace StayMate.Migrations
{
    [DbContext(typeof(StayMateDbContext))]
    partial class StayMateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StayMate.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostId")
                        .HasColumnType("int")
                        .HasColumnName("HostID");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int")
                        .HasColumnName("RequesterID");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AppointmentId");

                    b.HasIndex("HostId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("RoomId");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("StayMate.Models.CompatibilityScore", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ScoreID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreId"));

                    b.Property<DateTime?>("CalculatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("CompatibilityScore1")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("CompatibilityScore");

                    b.Property<decimal?>("InterestScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("LifestyleScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("LocationScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("User1Id")
                        .HasColumnType("int")
                        .HasColumnName("User1ID");

                    b.Property<int>("User2Id")
                        .HasColumnType("int")
                        .HasColumnName("User2ID");

                    b.HasKey("ScoreId")
                        .HasName("PK__Compatib__7DD229F1773F8E49");

                    b.HasIndex("User2Id");

                    b.HasIndex(new[] { "User1Id", "User2Id" }, "UQ_CompatibilityScore")
                        .IsUnique();

                    b.ToTable("CompatibilityScores", (string)null);
                });

            modelBuilder.Entity("StayMate.Models.Conversation", b =>
                {
                    b.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConversationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("datetime");

                    b.Property<int>("MatchId")
                        .HasColumnType("int")
                        .HasColumnName("MatchID");

                    b.HasKey("ConversationId")
                        .HasName("PK__Conversa__C050D8972EE1ADEC");

                    b.HasIndex(new[] { "MatchId" }, "UQ__Conversa__4218C836290942BB")
                        .IsUnique();

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("StayMate.Models.Interest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InterestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestId"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("IconURL");

                    b.Property<string>("InterestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InterestId")
                        .HasName("PK__Interest__20832C0759DDE1F1");

                    b.HasIndex(new[] { "InterestName" }, "UQ__Interest__D2704B36E4131C3E")
                        .IsUnique();

                    b.ToTable("Interests", (string)null);
                });

            modelBuilder.Entity("StayMate.Models.LifestylePreference", b =>
                {
                    b.Property<int>("PreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PreferenceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreferenceId"));

                    b.Property<int?>("CleanlinessLevel")
                        .HasColumnType("int");

                    b.Property<string>("CookingFrequency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DrinkingStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GuestFrequency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("HasPets")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("NoiseLevel")
                        .HasColumnType("int");

                    b.Property<string>("PetType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SleepTime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SmokingStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<string>("WakeUpTime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("WorkFromHome")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("PreferenceId")
                        .HasName("PK__Lifestyl__E228490FC3C93FE2");

                    b.HasIndex(new[] { "UserId" }, "UQ__Lifestyl__1788CCAD6DFEE750")
                        .IsUnique();

                    b.ToTable("LifestylePreferences", (string)null);
                });

            modelBuilder.Entity("StayMate.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MatchID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchId"));

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("MatchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("UnmatchedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("UnmatchedBy")
                        .HasColumnType("int");

                    b.Property<int>("User1Id")
                        .HasColumnType("int")
                        .HasColumnName("User1ID");

                    b.Property<int>("User2Id")
                        .HasColumnType("int")
                        .HasColumnName("User2ID");

                    b.HasKey("MatchId")
                        .HasName("PK__Matches__4218C837F1615985");

                    b.HasIndex("UnmatchedBy");

                    b.HasIndex("User2Id");

                    b.HasIndex(new[] { "User1Id", "User2Id" }, "IX_Matches_Users");

                    b.HasIndex(new[] { "User1Id", "User2Id" }, "UQ_Match")
                        .IsUnique();

                    b.ToTable("Matches", null, t =>
                        {
                            t.HasTrigger("TR_Matches_AutoChat");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("StayMate.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MessageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("ConversationID");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MediaURL");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("MessageType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Text");

                    b.Property<int>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("SenderID");

                    b.Property<DateTime?>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MessageId")
                        .HasName("PK__Messages__C87C037C4AC54BB5");

                    b.HasIndex("SenderId");

                    b.HasIndex(new[] { "ConversationId" }, "IX_Messages_Conversation");

                    b.ToTable("Messages", null, t =>
                        {
                            t.HasTrigger("TR_Messages_UpdateChatTime");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("StayMate.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Content")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NotificationType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E329A420D12");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("StayMate.Models.PaymentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LandlordId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VnPayTransactionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("LandlordId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TenantId");

                    b.ToTable("PaymentTransactions", (string)null);
                });

            modelBuilder.Entity("StayMate.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReviewID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int")
                        .HasColumnName("ReviewerID");

                    b.Property<int?>("TargetRoomId")
                        .HasColumnType("int")
                        .HasColumnName("TargetRoomID");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("int")
                        .HasColumnName("TargetUserID");

                    b.HasKey("ReviewId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("TargetRoomId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("StayMate.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Amenities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("AreaSqm")
                        .HasColumnType("float");

                    b.Property<DateTime?>("BoostExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HostUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBoosted")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomId");

                    b.HasIndex("HostUserId");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("StayMate.Models.RoomPhoto", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoId"));

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PhotoId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomPhotos", (string)null);
                });

            modelBuilder.Entity("StayMate.Models.RoomPreference", b =>
                {
                    b.Property<int>("RoomPreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoomPreferenceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomPreferenceId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("MaxBudget")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MinBudget")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly?>("MoveInDate")
                        .HasColumnType("date");

                    b.Property<int?>("PreferredAgeMax")
                        .HasColumnType("int");

                    b.Property<int?>("PreferredAgeMin")
                        .HasColumnType("int");

                    b.Property<string>("PreferredGender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PreferredRoomType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("RoomPreferenceId")
                        .HasName("PK__RoomPref__BB609FA3E4F9A2FC");

                    b.HasIndex(new[] { "UserId" }, "UQ__RoomPref__1788CCAD1BC6D05B")
                        .IsUnique();

                    b.ToTable("RoomPreferences", (string)null);
                });

            modelBuilder.Entity("StayMate.Models.Swipe", b =>
                {
                    b.Property<int>("SwipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SwipeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SwipeId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SwipeType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TargetUserId")
                        .HasColumnType("int")
                        .HasColumnName("TargetUserID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("SwipeId")
                        .HasName("PK__Swipes__486E327C51CAC5F1");

                    b.HasIndex("TargetUserId");

                    b.HasIndex(new[] { "UserId", "TargetUserId" }, "IX_Swipes_UserTarget");

                    b.HasIndex(new[] { "UserId", "TargetUserId" }, "UQ_Swipe")
                        .IsUnique();

                    b.ToTable("Swipes", (string)null);
                });

            modelBuilder.Entity("StayMate.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AccountStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AvatarURL");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("PremiumExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Student");

                    b.Property<string>("School")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC91A1B1A2");

                    b.HasIndex(new[] { "Email" }, "IX_Users_Email");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534423390EE")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasTrigger("TR_Users_Timestamp");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("StayMate.Models.UserInterest", b =>
                {
                    b.Property<int>("UserInterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserInterestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserInterestId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("InterestId")
                        .HasColumnType("int")
                        .HasColumnName("InterestID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("UserInterestId")
                        .HasName("PK__UserInte__28E6EBDEF6F47DEB");

                    b.HasIndex("InterestId");

                    b.HasIndex(new[] { "UserId", "InterestId" }, "UQ_UserInterest")
                        .IsUnique();

                    b.ToTable("UserInterests", (string)null);
                });

            modelBuilder.Entity("StayMate.Models.UserLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LocationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsPreferred")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10, 8)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11, 8)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<string>("Ward")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LocationId")
                        .HasName("PK__UserLoca__E7FEA477E23E9DFE");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "City", "District" }, "IX_UserLocations_City");

                    b.ToTable("UserLocations", (string)null);
                });

            modelBuilder.Entity("StayMate.Models.UserPhoto", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhotoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoId"));

                    b.Property<int?>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool?>("IsProfilePhoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PhotoURL");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("PhotoId")
                        .HasName("PK__UserPhot__21B7B582754E344C");

                    b.HasIndex("UserId");

                    b.ToTable("UserPhotos", (string)null);
                });

            modelBuilder.Entity("StayMate.Models.VerificationRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("AdminNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DocumentImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("RequestId");

                    b.HasIndex("UserId");

                    b.ToTable("VerificationRequests", (string)null);
                });

            modelBuilder.Entity("StayMate.Models.Appointment", b =>
                {
                    b.HasOne("StayMate.Models.User", "Host")
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StayMate.Models.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StayMate.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Host");

                    b.Navigation("Requester");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("StayMate.Models.CompatibilityScore", b =>
                {
                    b.HasOne("StayMate.Models.User", "User1")
                        .WithMany("CompatibilityScoreUser1s")
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Compatibi__User1__00200768");

                    b.HasOne("StayMate.Models.User", "User2")
                        .WithMany("CompatibilityScoreUser2s")
                        .HasForeignKey("User2Id")
                        .IsRequired()
                        .HasConstraintName("FK__Compatibi__User2__01142BA1");

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("StayMate.Models.Conversation", b =>
                {
                    b.HasOne("StayMate.Models.Match", "Match")
                        .WithOne("Conversation")
                        .HasForeignKey("StayMate.Models.Conversation", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Conversat__Match__73BA3083");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("StayMate.Models.LifestylePreference", b =>
                {
                    b.HasOne("StayMate.Models.User", "User")
                        .WithOne("LifestylePreference")
                        .HasForeignKey("StayMate.Models.LifestylePreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Lifestyle__UserI__52593CB8");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StayMate.Models.Match", b =>
                {
                    b.HasOne("StayMate.Models.User", "UnmatchedByNavigation")
                        .WithMany("MatchUnmatchedByNavigations")
                        .HasForeignKey("UnmatchedBy")
                        .HasConstraintName("FK__Matches__Unmatch__6E01572D");

                    b.HasOne("StayMate.Models.User", "User1")
                        .WithMany("MatchUser1s")
                        .HasForeignKey("User1Id")
                        .IsRequired()
                        .HasConstraintName("FK__Matches__User1ID__6C190EBB");

                    b.HasOne("StayMate.Models.User", "User2")
                        .WithMany("MatchUser2s")
                        .HasForeignKey("User2Id")
                        .IsRequired()
                        .HasConstraintName("FK__Matches__User2ID__6D0D32F4");

                    b.Navigation("UnmatchedByNavigation");

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("StayMate.Models.Message", b =>
                {
                    b.HasOne("StayMate.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Messages__Conver__7A672E12");

                    b.HasOne("StayMate.Models.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .IsRequired()
                        .HasConstraintName("FK__Messages__Sender__7B5B524B");

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("StayMate.Models.Notification", b =>
                {
                    b.HasOne("StayMate.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__UserI__05D8E0BE");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StayMate.Models.PaymentTransaction", b =>
                {
                    b.HasOne("StayMate.Models.User", "Landlord")
                        .WithMany("LandlordTransactions")
                        .HasForeignKey("LandlordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StayMate.Models.Room", "Room")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StayMate.Models.User", "Tenant")
                        .WithMany("TenantTransactions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Landlord");

                    b.Navigation("Room");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("StayMate.Models.Review", b =>
                {
                    b.HasOne("StayMate.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StayMate.Models.Room", "TargetRoom")
                        .WithMany()
                        .HasForeignKey("TargetRoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StayMate.Models.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Reviewer");

                    b.Navigation("TargetRoom");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("StayMate.Models.Room", b =>
                {
                    b.HasOne("StayMate.Models.User", "HostUser")
                        .WithMany("Rooms")
                        .HasForeignKey("HostUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HostUser");
                });

            modelBuilder.Entity("StayMate.Models.RoomPhoto", b =>
                {
                    b.HasOne("StayMate.Models.Room", "Room")
                        .WithMany("Photos")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("StayMate.Models.RoomPreference", b =>
                {
                    b.HasOne("StayMate.Models.User", "User")
                        .WithOne("RoomPreference")
                        .HasForeignKey("StayMate.Models.RoomPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__RoomPrefe__UserI__5FB337D6");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StayMate.Models.Swipe", b =>
                {
                    b.HasOne("StayMate.Models.User", "TargetUser")
                        .WithMany("SwipeTargetUsers")
                        .HasForeignKey("TargetUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Swipes__TargetUs__66603565");

                    b.HasOne("StayMate.Models.User", "User")
                        .WithMany("SwipeUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Swipes__UserID__656C112C");

                    b.Navigation("TargetUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StayMate.Models.UserInterest", b =>
                {
                    b.HasOne("StayMate.Models.Interest", "Interest")
                        .WithMany("UserInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserInter__Inter__5AEE82B9");

                    b.HasOne("StayMate.Models.User", "User")
                        .WithMany("UserInterests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserInter__UserI__59FA5E80");

                    b.Navigation("Interest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StayMate.Models.UserLocation", b =>
                {
                    b.HasOne("StayMate.Models.User", "User")
                        .WithMany("UserLocations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserLocat__UserI__4316F928");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StayMate.Models.UserPhoto", b =>
                {
                    b.HasOne("StayMate.Models.User", "User")
                        .WithMany("UserPhotos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserPhoto__UserI__48CFD27E");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StayMate.Models.VerificationRequest", b =>
                {
                    b.HasOne("StayMate.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VerificationRequests_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StayMate.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("StayMate.Models.Interest", b =>
                {
                    b.Navigation("UserInterests");
                });

            modelBuilder.Entity("StayMate.Models.Match", b =>
                {
                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("StayMate.Models.Room", b =>
                {
                    b.Navigation("PaymentTransactions");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("StayMate.Models.User", b =>
                {
                    b.Navigation("CompatibilityScoreUser1s");

                    b.Navigation("CompatibilityScoreUser2s");

                    b.Navigation("LandlordTransactions");

                    b.Navigation("LifestylePreference");

                    b.Navigation("MatchUnmatchedByNavigations");

                    b.Navigation("MatchUser1s");

                    b.Navigation("MatchUser2s");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("RoomPreference");

                    b.Navigation("Rooms");

                    b.Navigation("SwipeTargetUsers");

                    b.Navigation("SwipeUsers");

                    b.Navigation("TenantTransactions");

                    b.Navigation("UserInterests");

                    b.Navigation("UserLocations");

                    b.Navigation("UserPhotos");
                });
#pragma warning restore 612, 618
        }
    }
}
